In [3]:
import pandas as pd

In [4]:
df=pd.read_excel("unclean_employee_dataset.xlsx")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  1000 non-null   int64
 1   Name        1000 non-null   object
 2   Department  743 non-null    object
 3   Email       798 non-null    object
 4   Phone       869 non-null    float64
 5   Salary      504 non-null    float64
 6   JoinDate    910 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 54.8+ KB

In [6]:
df.head()

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
0,51,Sara,Operations,sara51@mail.com,3.312962e+09,146056.0,2019-05-15
1,299,Ahmed,IT,ahmed299@company.com,3.390091e+09,NaN,2015-02-12
2,573,Sara,NaN,sara573@company.com,NaN,0.0,2023-12-29
3,340,Ahmed,Finance,ahmed340@,3.031268e+09,NaN,2024-08-22
4,39,Ali,HR,ali39@,3.149136e+09,NaN,2020-09-18

In [7]:
df.isnull().sum()

EmployeeID      0
Name            0
Department    257
Email         202
Phone         131
Salary        496
JoinDate       90
dtype: int64

In [8]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999    False
Length: 1000, dtype: bool

In [9]:
df.duplicated().sum()

np.int64(100)

In [10]:
df[df.duplicated()]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
94,377,Sara,IT,sara377@,3.355945e+09,81537.0,2018-08-28
206,846,Ayesha,IT,ayesha846@mail.com,3.011056e+09,NaN,2021-03-11
214,452,Ayesha,Finance,ayesha452@company.com,3.463973e+09,NaN,2021-07-23
224,833,Bilal,HR,NaN,3.430804e+09,NaN,2017-11-15
238,692,Usman,Operations,usman692@company.com,3.240004e+09,0.0,2022-06-25
...,...,...,...,...,...,...,...
966,342,Sara,IT,sara342@,3.384353e+09,70684.0,2018-10-12
974,355,Noor,Operations,noor355@company.com,3.468901e+09,NaN,2020-03-15
991,386,Ali,NaN,ali386@,3.138366e+09,41422.0,2018-10-27
992,20,Noor,Sales,noor20@None,NaN,NaN,2023-10-19
997,858,Fatima,Finance,fatima858@,3.482932e+09,NaN,2021-12-21

In [11]:
df['Salary']

0      146056.0
1           NaN
2           0.0
3           NaN
4           NaN
         ...
995         NaN
996         NaN
997         NaN
998         NaN
999         NaN
Name: Salary, Length: 1000, dtype: float64

In [12]:
df['Salary'].isnull()

0      False
1       True
2      False
3       True
4       True
       ...
995     True
996     True
997     True
998     True
999     True
Name: Salary, Length: 1000, dtype: bool

In [13]:
df['Salary'].isnull().sum()

np.int64(496)

In [14]:
df[df['Salary'].isnull()]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
1,299,Ahmed,IT,ahmed299@company.com,3.390091e+09,NaN,2015-02-12
3,340,Ahmed,Finance,ahmed340@,3.031268e+09,NaN,2024-08-22
4,39,Ali,HR,ali39@,3.149136e+09,NaN,2020-09-18
5,287,Ahmed,Operations,ahmed287@,3.012711e+09,NaN,2024-08-28
10,253,Ahmed,Sales,ahmed253@mail.com,3.051839e+09,NaN,2015-08-31
...,...,...,...,...,...,...,...
995,706,Sara,HR,NaN,3.384409e+09,NaN,2022-08-11
996,633,Fatima,NaN,fatima633@,3.139734e+09,NaN,2019-08-02
997,858,Fatima,Finance,fatima858@,3.482932e+09,NaN,2021-12-21
998,809,Fatima,NaN,fatima809@mail.com,NaN,NaN,2023-10-18
999,695,Ali,HR,NaN,3.168388e+09,NaN,2020-01-31

In [15]:
df.isnull().sum()

EmployeeID      0
Name            0
Department    257
Email         202
Phone         131
Salary        496
JoinDate       90
dtype: int64

In [16]:
df["Department"]

0      Operations
1              IT
2             NaN
3         Finance
4              HR
          ...
995            HR
996           NaN
997       Finance
998           NaN
999            HR
Name: Department, Length: 1000, dtype: object

In [17]:
df["Department"].isnull()

0      False
1      False
2       True
3      False
4      False
       ...
995    False
996     True
997    False
998     True
999    False
Name: Department, Length: 1000, dtype: bool

In [18]:
df["Department"].isnull().sum()

np.int64(257)

In [19]:
df[df["Salary"].isnull()]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
1,299,Ahmed,IT,ahmed299@company.com,3.390091e+09,NaN,2015-02-12
3,340,Ahmed,Finance,ahmed340@,3.031268e+09,NaN,2024-08-22
4,39,Ali,HR,ali39@,3.149136e+09,NaN,2020-09-18
5,287,Ahmed,Operations,ahmed287@,3.012711e+09,NaN,2024-08-28
10,253,Ahmed,Sales,ahmed253@mail.com,3.051839e+09,NaN,2015-08-31
...,...,...,...,...,...,...,...
995,706,Sara,HR,NaN,3.384409e+09,NaN,2022-08-11
996,633,Fatima,NaN,fatima633@,3.139734e+09,NaN,2019-08-02
997,858,Fatima,Finance,fatima858@,3.482932e+09,NaN,2021-12-21
998,809,Fatima,NaN,fatima809@mail.com,NaN,NaN,2023-10-18
999,695,Ali,HR,NaN,3.168388e+09,NaN,2020-01-31

In [20]:
df["Salary"].duplicated().sum()

np.int64(751)

In [21]:
df[df['Phone'].isnull()]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
2,573,Sara,NaN,sara573@company.com,NaN,0.0,2023-12-29
15,179,Ahmed,IT,ahmed179@company.com,NaN,0.0,2021-10-13
39,395,Ahmed,NaN,NaN,NaN,38699.0,2017-08-18
41,194,Ayesha,Marketing,ayesha194@mail.com,NaN,0.0,2016-09-16
65,385,Ayesha,Sales,ayesha385@company.com,NaN,NaN,2021-11-27
...,...,...,...,...,...,...,...
947,677,Noor,Marketing,noor677@company.com,NaN,NaN,2015-04-29
956,570,Bilal,Finance,bilal570@company.com,NaN,NaN,2021-01-14
972,874,Ahmed,Operations,ahmed874@mail.com,NaN,139781.0,2017-05-27
992,20,Noor,Sales,noor20@None,NaN,NaN,2023-10-19
998,809,Fatima,NaN,fatima809@mail.com,NaN,NaN,2023-10-18

In [22]:
df[df["Department"].isnull()]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
2,573,Sara,NaN,sara573@company.com,NaN,0.0,2023-12-29
7,801,Sara,NaN,NaN,3.440737e+09,41445.0,2018-04-18
9,896,Bilal,NaN,NaN,3.221649e+09,0.0,2018-04-30
13,840,Zainab,NaN,zainab840@company.com,3.492560e+09,0.0,2019-10-05
25,475,Noor,NaN,NaN,3.221270e+09,NaN,2021-10-29
...,...,...,...,...,...,...,...
986,653,Ayesha,NaN,ayesha653@,3.052410e+09,138925.0,2017-04-21
991,386,Ali,NaN,ali386@,3.138366e+09,41422.0,2018-10-27
993,206,Usman,NaN,usman206@None,3.417780e+09,NaN,2021-01-15
996,633,Fatima,NaN,fatima633@,3.139734e+09,NaN,2019-08-02
998,809,Fatima,NaN,fatima809@mail.com,NaN,NaN,2023-10-18

In [32]:
data=pd.DataFrame(
    {"Name":["ali","hassan","hassan","hassan","ubaid"],'age':[18,19,17,19,22], "marks":[60,57,29,57,32]})

In [33]:
data

     Name  age  marks
0     ali   18     60
1  hassan   19     57
2  hassan   17     29
3  hassan   19     57
4   ubaid   22     32

In [34]:
data.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [35]:
data[data.duplicated()]

     Name  age  marks
3  hassan   19     57

In [36]:
data.duplicated().sum()

np.int64(1)

In [37]:
data.duplicated(["Name"])

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [44]:
data.duplicated(subset=["age"])

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [45]:
data.duplicated(subset=["marks"])

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [46]:
data.duplicated(subset=["marks"])

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [47]:
data.duplicated(["age"]).sum()

np.int64(1)

In [51]:
data.duplicated(['Name']).sum()

np.int64(2)

In [52]:
data.duplicated().sum()

np.int64(1)

In [53]:
data.duplicated(subset=["Name","age"])

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [54]:
data.duplicated(subset=["Name","age"]).sum()

np.int64(1)

In [59]:
data[data.duplicated(subset=["Name","age"])]

     Name  age  marks
3  hassan   19     57

In [63]:
data[data.duplicated(subset=["Name"])]

     Name  age  marks
2  hassan   17     29
3  hassan   19     57

In [65]:
data[data.duplicated(subset=["Name"])]

     Name  age  marks
2  hassan   17     29
3  hassan   19     57

In [68]:
data[data.duplicated(keep="first")]

     Name  age  marks
3  hassan   19     57

In [69]:
data[data.duplicated(keep="last")]

     Name  age  marks
1  hassan   19     57

In [70]:
df.drop_duplicates(inplace=True)

In [72]:
df.duplicated().sum()

np.int64(0)

In [75]:
df.isnull().sum().sum() #total sum of null values

np.int64(1056)

In [80]:
df.shape[0] #this givs the total number of rows

900

In [81]:
df.shape[1]

7

In [82]:
df.shape[0]*df.shape[1]

6300

In [83]:
df.shape

(900, 7)

In [85]:
df.shape[0]

900

In [86]:
df.shape[1]

7

In [91]:
df.dropna()

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
0,51,Sara,Operations,sara51@mail.com,3.312962e+09,146056.0,2019-05-15
8,177,Fatima,HR,fatima177@,3.338796e+09,0.0,2022-05-08
14,146,Sara,IT,sara146@mail.com,3.233094e+09,143136.0,2020-04-09
17,361,Fatima,Marketing,fatima361@company.com,3.163917e+09,71694.0,2023-04-12
19,256,Zainab,HR,zainab256@company.com,3.480660e+09,63350.0,2022-08-11
...,...,...,...,...,...,...,...
977,529,Noor,Finance,noor529@company.com,3.334203e+09,109256.0,2018-06-24
981,86,Ahmed,Sales,ahmed86@,3.091260e+09,64021.0,2024-09-04
983,704,Usman,Operations,usman704@None,3.342778e+09,0.0,2023-03-20
985,351,Sara,Sales,sara351@company.com,3.489999e+09,106442.0,2023-03-23
990,888,Usman,Marketing,usman888@,3.427257e+09,98799.0,2019-08-01

In [93]:
df.isnull().sum()

EmployeeID      0
Name            0
Department    232
Email         180
Phone         121
Salary        438
JoinDate       85
dtype: int64

In [94]:
df.dropna(inplace=True)

In [95]:
df.isnull()

     EmployeeID   Name  Department  Email  Phone  Salary  JoinDate
0         False  False       False  False  False   False     False
8         False  False       False  False  False   False     False
14        False  False       False  False  False   False     False
17        False  False       False  False  False   False     False
19        False  False       False  False  False   False     False
..          ...    ...         ...    ...    ...     ...       ...
977       False  False       False  False  False   False     False
981       False  False       False  False  False   False     False
983       False  False       False  False  False   False     False
985       False  False       False  False  False   False     False
990       False  False       False  False  False   False     False

[213 rows x 7 columns]

In [99]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    0
Email         0
Phone         0
Salary        0
JoinDate      0
dtype: int64

In [100]:
df

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
0,51,Sara,Operations,sara51@mail.com,3.312962e+09,146056.0,2019-05-15
8,177,Fatima,HR,fatima177@,3.338796e+09,0.0,2022-05-08
14,146,Sara,IT,sara146@mail.com,3.233094e+09,143136.0,2020-04-09
17,361,Fatima,Marketing,fatima361@company.com,3.163917e+09,71694.0,2023-04-12
19,256,Zainab,HR,zainab256@company.com,3.480660e+09,63350.0,2022-08-11
...,...,...,...,...,...,...,...
977,529,Noor,Finance,noor529@company.com,3.334203e+09,109256.0,2018-06-24
981,86,Ahmed,Sales,ahmed86@,3.091260e+09,64021.0,2024-09-04
983,704,Usman,Operations,usman704@None,3.342778e+09,0.0,2023-03-20
985,351,Sara,Sales,sara351@company.com,3.489999e+09,106442.0,2023-03-23
990,888,Usman,Marketing,usman888@,3.427257e+09,98799.0,2019-08-01

In [104]:
df['EmployeeID'].unique()

array([ 51, 177, 146, 361, 256, 498, 127, 668, 891, 302, 164, 373, 378,
       811, 195,  82, 692, 377, 504, 616, 842, 292, 268, 722,  83, 523,
       463, 481,  74, 702, 531, 352,  94, 814, 821, 785, 788, 608, 554,
       289, 712, 189, 832,  61, 671, 415,  21, 124,  89, 269, 711, 485,
       342, 448, 129, 747, 310, 161, 648, 744, 625, 136, 542, 225, 382,
       145, 439, 144, 623, 401, 868, 158,   3, 200, 450, 535, 687, 652,
       438, 123, 166, 675, 306, 873, 417, 339, 877, 568, 585, 474, 642,
       794, 552, 533,  68, 674, 845, 171, 151, 170, 606, 493, 338, 182,
       774, 797, 445, 569, 419, 547,  56, 100, 587, 511, 211, 277, 734,
       267, 796, 248, 870, 673, 766, 645, 684,  88, 798, 222, 777, 592,
       235, 867, 442, 819, 770, 434, 436, 238, 215, 800, 193, 271, 155,
       723, 683, 105, 413, 602, 447, 443, 760, 662, 607, 620,  60, 407,
       562, 389, 276, 783, 636, 262, 588, 106, 426,  12,   2, 108, 329,
       470, 515, 318, 487, 327, 297, 191, 575,  30, 519, 296, 669, 371,
       563, 411, 841, 379, 263,  76, 757, 134, 469, 381,  22, 716, 178,
       169, 656, 466, 771, 497, 632, 705, 720, 880, 477, 133,  63, 860,
       529,  86, 704, 351, 888])

In [107]:
df["Name"].unique()

array(['Sara', 'Fatima', 'Zainab', 'Bilal', 'Usman', 'Ahmed', 'Ali',
       'Noor', 'Ayesha', 'Hassan'], dtype=object)

In [108]:
df["Name"].nunique()

10

In [110]:
df["Name"].value_counts()

Name
Zainab    32
Fatima    27
Usman     26
Sara      25
Noor      22
Ahmed     20
Ayesha    18
Ali       16
Hassan    14
Bilal     13
Name: count, dtype: int64

In [111]:
df["Name"].value_counts()

Name
Zainab    32
Fatima    27
Usman     26
Sara      25
Noor      22
Ahmed     20
Ayesha    18
Ali       16
Hassan    14
Bilal     13
Name: count, dtype: int64

In [112]:
df["Department"]

0      Operations
8              HR
14             IT
17      Marketing
19             HR
          ...
977       Finance
981         Sales
983    Operations
985         Sales
990     Marketing
Name: Department, Length: 213, dtype: object

In [113]:
df["Department"].unique()

array(['Operations', 'HR', 'IT', 'Marketing', 'Sales', 'Finance'],
      dtype=object)

In [114]:
df["Department"].nunique()

6

In [119]:
df[df["Department"]=="IT"]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
14,146,Sara,IT,sara146@mail.com,3.233094e+09,143136.0,2020-04-09
40,891,Bilal,IT,bilal891@mail.com,3.048155e+09,46117.0,2024-12-04
43,302,Usman,IT,usman302@None,3.282637e+09,0.0,2024-02-13
44,164,Ahmed,IT,ahmed164@,3.309543e+09,148425.0,2024-05-16
64,377,Sara,IT,sara377@,3.355945e+09,81537.0,2018-08-28
80,616,Sara,IT,sara616@mail.com,3.481368e+09,61465.0,2016-02-08
82,842,Usman,IT,usman842@,3.048578e+09,0.0,2022-04-24
121,481,Ayesha,IT,ayesha481@None,3.256384e+09,55642.0,2022-10-11
127,702,Ayesha,IT,ayesha702@,3.032313e+09,51528.0,2021-08-04
169,554,Noor,IT,noor554@mail.com,3.225555e+09,33222.0,2015-10-02
194,415,Noor,IT,noor415@None,3.180092e+09,71456.0,2019-09-16
195,21,Zainab,IT,zainab21@company.com,3.433910e+09,147974.0,2018-08-14
204,269,Usman,IT,usman269@,3.201077e+09,0.0,2019-11-15
220,711,Ali,IT,ali711@company.com,3.428733e+09,115862.0,2021-01-30
228,342,Sara,IT,sara342@,3.384353e+09,70684.0,2018-10-12
276,625,Ahmed,IT,ahmed625@None,3.427606e+09,79115.0,2024-10-11
277,136,Ahmed,IT,ahmed136@mail.com,3.205540e+09,77184.0,2018-04-25
299,145,Bilal,IT,bilal145@company.com,3.225080e+09,0.0,2021-10-21
342,3,Fatima,IT,fatima3@,3.138307e+09,44075.0,2021-12-07
369,652,Fatima,IT,fatima652@,3.288471e+09,0.0,2016-06-12
383,166,Usman,IT,usman166@None,3.493260e+09,0.0,2023-08-24
444,552,Fatima,IT,fatima552@company.com,3.379826e+09,133864.0,2019-07-30
474,493,Ayesha,IT,ayesha493@mail.com,3.156409e+09,0.0,2018-10-13
478,338,Ayesha,IT,ayesha338@company.com,3.288793e+09,32920.0,2023-04-06
530,100,Ayesha,IT,ayesha100@company.com,3.136582e+09,141116.0,2019-11-05
552,870,Ayesha,IT,ayesha870@,3.486706e+09,58524.0,2019-11-28
573,684,Usman,IT,usman684@,3.221027e+09,0.0,2018-06-28
577,798,Fatima,IT,fatima798@company.com,3.156286e+09,0.0,2022-04-30
638,238,Fatima,IT,fatima238@,3.476246e+09,102395.0,2016-05-25
647,193,Usman,IT,usman193@None,3.338576e+09,128813.0,2022-11-15
661,105,Noor,IT,noor105@company.com,3.090903e+09,0.0,2018-06-05
685,760,Noor,IT,noor760@,3.487275e+09,63050.0,2018-10-24
767,426,Sara,IT,sara426@,3.127971e+09,45176.0,2020-11-15
847,563,Hassan,IT,hassan563@,3.445589e+09,0.0,2019-03-29
916,771,Hassan,IT,hassan771@company.com,3.467351e+09,0.0,2021-06-09
924,497,Usman,IT,usman497@,3.312785e+09,0.0,2020-03-11

In [123]:
(df["Department"]=="IT").sum()

np.int64(36)

In [124]:
df["Name"]

0        Sara
8      Fatima
14       Sara
17     Fatima
19     Zainab
        ...
977      Noor
981     Ahmed
983     Usman
985      Sara
990     Usman
Name: Name, Length: 213, dtype: object

In [125]:
df["Name"]=="Zainab"

0      False
8      False
14     False
17     False
19      True
       ...
977    False
981    False
983    False
985    False
990    False
Name: Name, Length: 213, dtype: bool

In [126]:
(df["Name"]=="Zainab").sum()

np.int64(32)

In [131]:
df["Name"].unique()

array(['Sara', 'Fatima', 'Zainab', 'Bilal', 'Usman', 'Ahmed', 'Ali',
       'Noor', 'Ayesha', 'Hassan'], dtype=object)

In [132]:
(df["Name"]=="Fatima").sum()

np.int64(27)

In [133]:
df["Department"]=="IT"

0      False
8      False
14      True
17     False
19     False
       ...
977    False
981    False
983    False
985    False
990    False
Name: Department, Length: 213, dtype: bool

In [134]:
df[df["Department"]=="IT"]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
14,146,Sara,IT,sara146@mail.com,3.233094e+09,143136.0,2020-04-09
40,891,Bilal,IT,bilal891@mail.com,3.048155e+09,46117.0,2024-12-04
43,302,Usman,IT,usman302@None,3.282637e+09,0.0,2024-02-13
44,164,Ahmed,IT,ahmed164@,3.309543e+09,148425.0,2024-05-16
64,377,Sara,IT,sara377@,3.355945e+09,81537.0,2018-08-28
80,616,Sara,IT,sara616@mail.com,3.481368e+09,61465.0,2016-02-08
82,842,Usman,IT,usman842@,3.048578e+09,0.0,2022-04-24
121,481,Ayesha,IT,ayesha481@None,3.256384e+09,55642.0,2022-10-11
127,702,Ayesha,IT,ayesha702@,3.032313e+09,51528.0,2021-08-04
169,554,Noor,IT,noor554@mail.com,3.225555e+09,33222.0,2015-10-02
194,415,Noor,IT,noor415@None,3.180092e+09,71456.0,2019-09-16
195,21,Zainab,IT,zainab21@company.com,3.433910e+09,147974.0,2018-08-14
204,269,Usman,IT,usman269@,3.201077e+09,0.0,2019-11-15
220,711,Ali,IT,ali711@company.com,3.428733e+09,115862.0,2021-01-30
228,342,Sara,IT,sara342@,3.384353e+09,70684.0,2018-10-12
276,625,Ahmed,IT,ahmed625@None,3.427606e+09,79115.0,2024-10-11
277,136,Ahmed,IT,ahmed136@mail.com,3.205540e+09,77184.0,2018-04-25
299,145,Bilal,IT,bilal145@company.com,3.225080e+09,0.0,2021-10-21
342,3,Fatima,IT,fatima3@,3.138307e+09,44075.0,2021-12-07
369,652,Fatima,IT,fatima652@,3.288471e+09,0.0,2016-06-12
383,166,Usman,IT,usman166@None,3.493260e+09,0.0,2023-08-24
444,552,Fatima,IT,fatima552@company.com,3.379826e+09,133864.0,2019-07-30
474,493,Ayesha,IT,ayesha493@mail.com,3.156409e+09,0.0,2018-10-13
478,338,Ayesha,IT,ayesha338@company.com,3.288793e+09,32920.0,2023-04-06
530,100,Ayesha,IT,ayesha100@company.com,3.136582e+09,141116.0,2019-11-05
552,870,Ayesha,IT,ayesha870@,3.486706e+09,58524.0,2019-11-28
573,684,Usman,IT,usman684@,3.221027e+09,0.0,2018-06-28
577,798,Fatima,IT,fatima798@company.com,3.156286e+09,0.0,2022-04-30
638,238,Fatima,IT,fatima238@,3.476246e+09,102395.0,2016-05-25
647,193,Usman,IT,usman193@None,3.338576e+09,128813.0,2022-11-15
661,105,Noor,IT,noor105@company.com,3.090903e+09,0.0,2018-06-05
685,760,Noor,IT,noor760@,3.487275e+09,63050.0,2018-10-24
767,426,Sara,IT,sara426@,3.127971e+09,45176.0,2020-11-15
847,563,Hassan,IT,hassan563@,3.445589e+09,0.0,2019-03-29
916,771,Hassan,IT,hassan771@company.com,3.467351e+09,0.0,2021-06-09
924,497,Usman,IT,usman497@,3.312785e+09,0.0,2020-03-11

In [141]:
df[df["Department"]=='IT'].shape

(36, 7)

In [142]:
df["Email"].unique()

array(['sara51@mail.com', 'fatima177@', 'sara146@mail.com',
       'fatima361@company.com', 'zainab256@company.com',
       'sara498@company.com', 'zainab127@mail.com', 'fatima668@None',
       'bilal891@mail.com', 'usman302@None', 'ahmed164@',
       'fatima373@None', 'zainab378@None', 'ali811@', 'noor195@None',
       'sara82@None', 'usman692@company.com', 'sara377@',
       'sara504@mail.com', 'sara616@mail.com', 'usman842@', 'noor292@',
       'zainab268@company.com', 'sara722@', 'zainab83@company.com',
       'zainab523@', 'noor463@mail.com', 'ayesha481@None',
       'ayesha74@mail.com', 'ayesha702@', 'noor531@None',
       'fatima352@company.com', 'ayesha94@', 'noor814@', 'noor821@',
       'ali785@mail.com', 'ali788@mail.com', 'zainab608@mail.com',
       'noor554@mail.com', 'fatima289@company.com', 'usman712@',
       'noor189@', 'sara832@', 'zainab61@company.com',
       'fatima671@company.com', 'noor415@None', 'zainab21@company.com',
       'noor124@', 'usman89@', 'usman269@', 'ali711@company.com',
       'fatima485@', 'sara342@', 'noor448@mail.com', 'fatima129@None',
       'usman747@company.com', 'hassan310@mail.com',
       'sara161@company.com', 'bilal648@company.com', 'sara744@None',
       'ahmed625@None', 'ahmed136@mail.com', 'usman542@',
       'zainab225@company.com', 'ali382@mail.com', 'bilal145@company.com',
       'zainab439@', 'ahmed144@None', 'noor623@None',
       'fatima401@mail.com', 'ayesha868@mail.com', 'zainab158@None',
       'fatima3@', 'ayesha200@company.com', 'zainab450@',
       'ayesha535@None', 'fatima687@', 'fatima652@', 'ali438@None',
       'ayesha123@', 'usman166@None', 'ayesha675@company.com',
       'zainab306@mail.com', 'zainab873@None', 'zainab417@None',
       'sara339@None', 'ahmed877@mail.com', 'usman568@mail.com',
       'hassan585@mail.com', 'ali474@', 'ayesha642@company.com',
       'usman794@company.com', 'fatima552@company.com', 'hassan533@',
       'sara68@None', 'fatima674@', 'bilal845@None', 'sara171@None',
       'fatima151@company.com', 'sara170@company.com',
       'zainab606@mail.com', 'ayesha493@mail.com',
       'ayesha338@company.com', 'bilal182@None', 'sara774@',
       'ali797@mail.com', 'ahmed445@', 'noor569@None',
       'noor419@company.com', 'usman547@mail.com', 'ahmed56@company.com',
       'ayesha100@company.com', 'zainab587@mail.com', 'usman511@',
       'noor211@None', 'bilal277@None', 'usman734@company.com',
       'hassan267@None', 'ali796@', 'ahmed248@', 'ayesha870@',
       'hassan673@', 'zainab766@mail.com', 'hassan645@None', 'usman684@',
       'zainab88@mail.com', 'fatima798@company.com',
       'noor222@company.com', 'bilal777@None', 'zainab592@company.com',
       'usman235@None', 'zainab867@mail.com', 'noor442@', 'usman819@None',
       'bilal770@company.com', 'ali434@mail.com', 'ali436@', 'fatima238@',
       'usman215@', 'ali800@None', 'usman193@None', 'noor271@',
       'ayesha155@None', 'fatima723@', 'zainab683@company.com',
       'noor105@company.com', 'ayesha413@mail.com',
       'fatima602@company.com', 'zainab447@None', 'ali443@company.com',
       'noor760@', 'ahmed662@None', 'ahmed607@None',
       'zainab620@company.com', 'sara60@', 'bilal407@', 'hassan562@',
       'bilal389@mail.com', 'ali276@mail.com', 'hassan783@None',
       'fatima636@', 'usman262@', 'noor588@None', 'ahmed106@', 'sara426@',
       'ahmed12@', 'usman2@company.com', 'ahmed108@None',
       'bilal329@company.com', 'ahmed470@company.com',
       'ahmed515@company.com', 'ahmed318@company.com',
       'hassan487@mail.com', 'ahmed327@', 'ali297@company.com',
       'ali191@company.com', 'zainab575@None', 'fatima30@None',
       'zainab519@', 'usman296@company.com', 'bilal669@mail.com',
       'zainab371@None', 'hassan563@', 'hassan411@company.com',
       'hassan841@', 'ahmed379@company.com', 'fatima263@',
       'sara76@mail.com', 'zainab757@mail.com', 'fatima134@None',
       'fatima469@mail.com', 'ahmed381@', 'ayesha22@mail.com',
       'fatima716@company.com', 'sara178@company.com',
       'fatima169@company.com', 'zainab656@', 'zainab466@company.com',
       'hassan771@company.com', 'usman497@', 'sara632@',
       'sara705@company.com', 'bilal720@None', 'ayesha880@company.com',
       'hassan477@company.com', 'usman133@company.com', 'sara63@None',
       'zainab860@company.com', 'noor529@company.com', 'ahmed86@',
       'usman704@None', 'sara351@company.com', 'usman888@'], dtype=object)

In [143]:
df["Email"].nunique()

213

In [145]:
def clean_email(email):
    if email.endswith("@"):
        return email+"gmail.com"
    elif email.endswith("None"):
        return email.replace("None","gmail.com")
    else:
        return email

In [146]:
df["Email"]=df['Email'].apply(clean_email)

In [147]:
df['Email'].unique()

array(['sara51@mail.com', 'fatima177@gmail.com', 'sara146@mail.com',
       'fatima361@company.com', 'zainab256@company.com',
       'sara498@company.com', 'zainab127@mail.com', 'fatima668@gmail.com',
       'bilal891@mail.com', 'usman302@gmail.com', 'ahmed164@gmail.com',
       'fatima373@gmail.com', 'zainab378@gmail.com', 'ali811@gmail.com',
       'noor195@gmail.com', 'sara82@gmail.com', 'usman692@company.com',
       'sara377@gmail.com', 'sara504@mail.com', 'sara616@mail.com',
       'usman842@gmail.com', 'noor292@gmail.com', 'zainab268@company.com',
       'sara722@gmail.com', 'zainab83@company.com', 'zainab523@gmail.com',
       'noor463@mail.com', 'ayesha481@gmail.com', 'ayesha74@mail.com',
       'ayesha702@gmail.com', 'noor531@gmail.com',
       'fatima352@company.com', 'ayesha94@gmail.com', 'noor814@gmail.com',
       'noor821@gmail.com', 'ali785@mail.com', 'ali788@mail.com',
       'zainab608@mail.com', 'noor554@mail.com', 'fatima289@company.com',
       'usman712@gmail.com', 'noor189@gmail.com', 'sara832@gmail.com',
       'zainab61@company.com', 'fatima671@company.com',
       'noor415@gmail.com', 'zainab21@company.com', 'noor124@gmail.com',
       'usman89@gmail.com', 'usman269@gmail.com', 'ali711@company.com',
       'fatima485@gmail.com', 'sara342@gmail.com', 'noor448@mail.com',
       'fatima129@gmail.com', 'usman747@company.com',
       'hassan310@mail.com', 'sara161@company.com',
       'bilal648@company.com', 'sara744@gmail.com', 'ahmed625@gmail.com',
       'ahmed136@mail.com', 'usman542@gmail.com', 'zainab225@company.com',
       'ali382@mail.com', 'bilal145@company.com', 'zainab439@gmail.com',
       'ahmed144@gmail.com', 'noor623@gmail.com', 'fatima401@mail.com',
       'ayesha868@mail.com', 'zainab158@gmail.com', 'fatima3@gmail.com',
       'ayesha200@company.com', 'zainab450@gmail.com',
       'ayesha535@gmail.com', 'fatima687@gmail.com',
       'fatima652@gmail.com', 'ali438@gmail.com', 'ayesha123@gmail.com',
       'usman166@gmail.com', 'ayesha675@company.com',
       'zainab306@mail.com', 'zainab873@gmail.com', 'zainab417@gmail.com',
       'sara339@gmail.com', 'ahmed877@mail.com', 'usman568@mail.com',
       'hassan585@mail.com', 'ali474@gmail.com', 'ayesha642@company.com',
       'usman794@company.com', 'fatima552@company.com',
       'hassan533@gmail.com', 'sara68@gmail.com', 'fatima674@gmail.com',
       'bilal845@gmail.com', 'sara171@gmail.com', 'fatima151@company.com',
       'sara170@company.com', 'zainab606@mail.com', 'ayesha493@mail.com',
       'ayesha338@company.com', 'bilal182@gmail.com', 'sara774@gmail.com',
       'ali797@mail.com', 'ahmed445@gmail.com', 'noor569@gmail.com',
       'noor419@company.com', 'usman547@mail.com', 'ahmed56@company.com',
       'ayesha100@company.com', 'zainab587@mail.com',
       'usman511@gmail.com', 'noor211@gmail.com', 'bilal277@gmail.com',
       'usman734@company.com', 'hassan267@gmail.com', 'ali796@gmail.com',
       'ahmed248@gmail.com', 'ayesha870@gmail.com', 'hassan673@gmail.com',
       'zainab766@mail.com', 'hassan645@gmail.com', 'usman684@gmail.com',
       'zainab88@mail.com', 'fatima798@company.com',
       'noor222@company.com', 'bilal777@gmail.com',
       'zainab592@company.com', 'usman235@gmail.com',
       'zainab867@mail.com', 'noor442@gmail.com', 'usman819@gmail.com',
       'bilal770@company.com', 'ali434@mail.com', 'ali436@gmail.com',
       'fatima238@gmail.com', 'usman215@gmail.com', 'ali800@gmail.com',
       'usman193@gmail.com', 'noor271@gmail.com', 'ayesha155@gmail.com',
       'fatima723@gmail.com', 'zainab683@company.com',
       'noor105@company.com', 'ayesha413@mail.com',
       'fatima602@company.com', 'zainab447@gmail.com',
       'ali443@company.com', 'noor760@gmail.com', 'ahmed662@gmail.com',
       'ahmed607@gmail.com', 'zainab620@company.com', 'sara60@gmail.com',
       'bilal407@gmail.com', 'hassan562@gmail.com', 'bilal389@mail.com',
       'ali276@mail.com', 'hassan783@gmail.com', 'fatima636@gmail.com',
       'usman262@gmail.com', 'noor588@gmail.com', 'ahmed106@gmail.com',
       'sara426@gmail.com', 'ahmed12@gmail.com', 'usman2@company.com',
       'ahmed108@gmail.com', 'bilal329@company.com',
       'ahmed470@company.com', 'ahmed515@company.com',
       'ahmed318@company.com', 'hassan487@mail.com', 'ahmed327@gmail.com',
       'ali297@company.com', 'ali191@company.com', 'zainab575@gmail.com',
       'fatima30@gmail.com', 'zainab519@gmail.com',
       'usman296@company.com', 'bilal669@mail.com', 'zainab371@gmail.com',
       'hassan563@gmail.com', 'hassan411@company.com',
       'hassan841@gmail.com', 'ahmed379@company.com',
       'fatima263@gmail.com', 'sara76@mail.com', 'zainab757@mail.com',
       'fatima134@gmail.com', 'fatima469@mail.com', 'ahmed381@gmail.com',
       'ayesha22@mail.com', 'fatima716@company.com',
       'sara178@company.com', 'fatima169@company.com',
       'zainab656@gmail.com', 'zainab466@company.com',
       'hassan771@company.com', 'usman497@gmail.com', 'sara632@gmail.com',
       'sara705@company.com', 'bilal720@gmail.com',
       'ayesha880@company.com', 'hassan477@company.com',
       'usman133@company.com', 'sara63@gmail.com',
       'zainab860@company.com', 'noor529@company.com',
       'ahmed86@gmail.com', 'usman704@gmail.com', 'sara351@company.com',
       'usman888@gmail.com'], dtype=object)

In [148]:
df["Salary"]

0      146056.0
8           0.0
14     143136.0
17      71694.0
19      63350.0
         ...
977    109256.0
981     64021.0
983         0.0
985    106442.0
990     98799.0
Name: Salary, Length: 213, dtype: float64

In [150]:
df["Salary"]>0

0       True
8      False
14      True
17      True
19      True
       ...
977     True
981     True
983    False
985     True
990     True
Name: Salary, Length: 213, dtype: bool

In [153]:
(df["Salary"]>0).sum()

np.int64(112)

In [154]:
df["Salary"].unique()

array([146056.,      0., 143136.,  71694.,  63350.,  46117., 148425.,
        41174.,  66373.,  32810.,  90378.,  81537.,  81959.,  61465.,
        95608.,  54482.,  55642., 104960.,  51528.,  42605.,  33222.,
       148320.,  87248.,  82654.,  71456., 147974., 146622., 115862.,
       147075.,  70684.,  82942.,  94409.,  51333.,  79115.,  77184.,
        89694., 141885.,  44075., 144272.,  70057.,  53321.,  97109.,
       125306.,  71592.,  71931.,  86925.,  98380., 104204.,  47405.,
       122953.,  72873.,  83797., 133864., 144609.,  40339.,  50858.,
       102682.,  32920., 105540., 108859.,  53120., 141116.,  94235.,
       145275.,  88532.,  87470.,  33301.,  58524.,  68526., 145521.,
        89124., 108623.,  39748., 131320.,  48874., 102395.,  73449.,
        56644., 128813., 110598.,  56135.,  70303.,  63050., 109669.,
        96146., 125643., 109167., 129251.,  45176., 101824.,  63011.,
       123597., 135605.,  68791., 111116.,  36138.,  70219.,  99177.,
        76037.,  85469.,  68365.,  61208., 126106.,  80037., 133300.,
        98925.,  99414.,  38781., 118867., 109256.,  64021., 106442.,
        98799.])

In [156]:
df[df["Salary"]>0]

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
0,51,Sara,Operations,sara51@mail.com,3.312962e+09,146056.0,2019-05-15
14,146,Sara,IT,sara146@mail.com,3.233094e+09,143136.0,2020-04-09
17,361,Fatima,Marketing,fatima361@company.com,3.163917e+09,71694.0,2023-04-12
19,256,Zainab,HR,zainab256@company.com,3.480660e+09,63350.0,2022-08-11
40,891,Bilal,IT,bilal891@mail.com,3.048155e+09,46117.0,2024-12-04
...,...,...,...,...,...,...,...
969,63,Sara,Finance,sara63@gmail.com,3.483326e+09,118867.0,2017-02-08
977,529,Noor,Finance,noor529@company.com,3.334203e+09,109256.0,2018-06-24
981,86,Ahmed,Sales,ahmed86@gmail.com,3.091260e+09,64021.0,2024-09-04
985,351,Sara,Sales,sara351@company.com,3.489999e+09,106442.0,2023-03-23
990,888,Usman,Marketing,usman888@gmail.com,3.427257e+09,98799.0,2019-08-01

In [157]:
df=df[df["Salary"]>0]

In [158]:
df

,EmployeeID,Name,Department,Email,Phone,Salary,JoinDate
0,51,Sara,Operations,sara51@mail.com,3.312962e+09,146056.0,2019-05-15
14,146,Sara,IT,sara146@mail.com,3.233094e+09,143136.0,2020-04-09
17,361,Fatima,Marketing,fatima361@company.com,3.163917e+09,71694.0,2023-04-12
19,256,Zainab,HR,zainab256@company.com,3.480660e+09,63350.0,2022-08-11
40,891,Bilal,IT,bilal891@mail.com,3.048155e+09,46117.0,2024-12-04
...,...,...,...,...,...,...,...
969,63,Sara,Finance,sara63@gmail.com,3.483326e+09,118867.0,2017-02-08
977,529,Noor,Finance,noor529@company.com,3.334203e+09,109256.0,2018-06-24
981,86,Ahmed,Sales,ahmed86@gmail.com,3.091260e+09,64021.0,2024-09-04
985,351,Sara,Sales,sara351@company.com,3.489999e+09,106442.0,2023-03-23
990,888,Usman,Marketing,usman888@gmail.com,3.427257e+09,98799.0,2019-08-01

In [162]:
df.to_csv("home revised employees dataset")

In [163]:
df.to_json("home revided employees dataset")

In [164]:
import os
os.getcwd()

'C:\\Users\\DELL\\Pictures\\Hustle\\AI and Data Science'